apiVersion: apps/v1
kind: Deployment
metadata:
  name: vea-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vea-backend
  template:
    metadata:
      labels:
        app: vea-backend
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: backend-pool 
      containers:
      - name: vea-backend
        image: us-docker.pkg.dev/gen-lang-client-0057517563/vea-service/vea-backend:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "7"
          limits:
            cpu: "8"
---
apiVersion: v1
kind: Service
metadata:
  name: vea-backend-service
spec:
  selector:
    app: vea-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 35.188.211.190
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vea-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vea-backend-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
