apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-edit
  labels:
    app: video-edit
spec:
  selector:
    matchLabels:
      app: video-edit
  template:
    metadata:
      labels:
        app: video-edit
    spec:
      containers:
        - name: video-edit-container
          image: us-docker.pkg.dev/gen-lang-client-0057517563/vea-service/video-edit:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "6"
              memory: "2Gi"
            limits:
              cpu: "8"
              memory: "7Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: video-edit-service
spec:
  selector:
    app: video-edit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP