apiVersion: apps/v1
kind: Deployment
metadata:
  name: vea-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vea-frontend
  template:
    metadata:
      labels:
        app: vea-frontend
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: frontend-pool
      containers:
      - name: vea-frontend
        image: us-docker.pkg.dev/gen-lang-client-0057517563/vea-service/vea-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: http://backend-service
        resources:
          requests:
            cpu: "1"
          limits:
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: vea-frontend-service
spec:
  selector:
    app: vea-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 34.123.184.43
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vea-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vea-frontend-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
