apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-edit-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"  # ðŸ‘ˆ For GKE ingress
    kubernetes.io/ingress.global-static-ip-name: "video-edit-ip"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: video-edit-service
                port:
                  number: 80